### ISSUE TITLE
[c0313584c707ac05b0f0d8ab] 2020-12-16 13:42:10: Exceção fatal do tipo “Error”

### ISSUE THREAD

**Issue by user987335** [WolfgangFahl/PDFEmbed#5]
I tried
```
<pdf>File:Cadastrodeprodutos.pdf</pdf>
```
and
```
<pdf width="500" height="300">File:Cadastrodeprodutos.pdf</pdf>
```
my configuration is the same of the example 

// Default width for the PDF object container.
$wgPdfEmbed['width'] = 800;

// Default height for the PDF object container.
$wgPdfEmbed['height'] = 1090;

//Allow user the usage of the pdf tag
$wgGroupPermissions['*']['embed_pdf'] = true;

I looked on the wiki version and the extension is loaded

**Comment by WolfgangFahl** [comment]
```
<pdf>File:Cadastrodeprodutos.pdf</pdf>
```
and
``` 
<pdf>Cadastrodeprodutos.pdf</pdf>
```
should indeed work depending on your wiki version. What version of MediaWiki are you using?
What is the language setting of your wiki? 


you can also use an url
```
<pdf>http://somedomain.somsuffix/somepath/Cadastrodeprodutos.pdf</pdf>
```

Is your wiki public - could you make your test file available If the wiki is not public so that i can show how it works ...

Please supply the full stackframe of your error by setting the debug flags.
see https://www.mediawiki.org/wiki/Manual:How_to_debug

**Comment by user987335** [comment]
Hi!

Thank you for answer me!

Whatever if I use “File:Cadastrodeprodutos.pdf ”or “Cadastrodeprodutos.pdf” The fatal error is shown

My wiki is private, and the version is 1.35.0. (I’ve installed the AWS Bitnami MediaWiki Image)

[cid:image001.png@01D6D450.5CBD9990]

[cid:image002.png@01D6D450.5CBD9990]



De: Wolfgang Fahl <notifications@github.com>
Enviada em: quinta-feira, 17 de dezembro de 2020 04:10
Para: WolfgangFahl/PDFEmbed <PDFEmbed@noreply.github.com>
Cc: Fabio Baldo <fabio@ibs.inf.br>; Author <author@noreply.github.com>
Assunto: Re: [WolfgangFahl/PDFEmbed] [c0313584c707ac05b0f0d8ab] 2020-12-16 13:42:10: Exceção fatal do tipo “Error” (#5)


File:Cadastrodeprodutos.pdf
and
Cadastrodeprodutos.pdf

you can also use an url

is what should work depending on your wiki version. What version of MediaWiki are you using?
Is your wiki public - could you make your test file available If the wiki is not public so that i can show how it works ...

**Comment by WolfgangFahl** [comment]
see issue #3 #4 and https://github.com/WolfgangFahl/PDFEmbed/commit/93ce76f752fdf117fa14cc34aa00a04594a63806 there the File: support was introduced. It is language and Wiki version dependend. You might want to simply comment out the line
```php
 $filename = self::removeFilePrefix($filename);
 ```
 to find out whether this is the culprit and try with a none prefix version. The code in removeFilePrefix tries to find out what "File:" might look like in your language e.g. "Datei:" in german. It's somewhat complicated and version dependend and i already tried to harden it. It would be great to know if your problem is in the same area.

So please supply the information about your language i assume you are using a pt for portuguese language setting and i don't know what the translation of "File:" to portuguese would be in mediawiki. 

Please also supply the stacktrace as requested.

You seem to have tried to supply images/screenshots which are unfortunately not visible.

**Comment by user987335** [comment]
Hi!

The Version is

MediaWiki | 1.35.0
PHP | 7.3.24 (fpm-fcgi)
MariaDB | 10.3.25-MariaDB
ICU | 63.1
Extention PDFEmbed	2.0.2	LGPL-3.0-only	Media handler extension for PDF files.	Alexia E. Smith

I'm using pt_br (Brazilian Portuguese) 
The translation for "File" is "Arquivo" in Portuguese 

I've changed the log_erro to on, but, nothing is different on the error message.

I tried to use with the complete URL, but, the fatal error continues: 
<pdf>http://18.208.179.209/images/3/38/Cadastrodeprodutos.pdf</pdf>

**Comment by WolfgangFahl** [comment]
see http://wiki.bitplan.com/index.php/PDFEmbed for how the http embed works. I still need the stack trace of your error which you'll find in your log file. What webserver and OS are you using e.g. Apache/Linux? Did you try uncommenting? I also offer to invite you for an online debug session.

**Comment by user987335** [comment]
I've replaced the files with the repository "git clone https://github.com/WolfgangFahl/PDFEmbed"
Now it is working!

Thank you again!


De: Wolfgang Fahl <notifications@github.com>
Enviada em: sexta-feira, 18 de dezembro de 2020 03:46
Para: WolfgangFahl/PDFEmbed <PDFEmbed@noreply.github.com>
Cc: Fabio Baldo <fabio@ibs.inf.br>; Author <author@noreply.github.com>
Assunto: Re: [WolfgangFahl/PDFEmbed] [c0313584c707ac05b0f0d8ab] 2020-12-16 13:42:10: Exceção fatal do tipo “Error” (#5)


see http://wiki.bitplan.com/index.php/PDFEmbed for how the http embed works. I still need the stack trace of your error which you'll find in your log file. What webserver and OS are you using e.g. Apache/Linux? Did you try uncommenting? I also offer to invite you for an online debug session.

**Comment by WolfgangFahl** [comment]
Great. Thx for the feedback.
